app/aviablog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flights.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/flights/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("passengers/", views.PassengersView.as_view(), name="passengers"),
    path("profile/<slug:username>/", views.ProfileView.as_view(), name="profile"),
    path("flight/<slug:usertripslug>/", views.FlightView.as_view(), name="flight"),
    path("flight/<slug:usertripslug>/update", views.FlightUpdateView.as_view(), name="flight_update"),
    path("flight/<slug:usertripslug>/delete", views.FlightDeleteView.as_view(), name="flight_delete"),
    path("add_flight/", views.AddFlightView.as_view(), name="add_flight")
]

# views.AddFlightView.as_view()

app/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from users.views import RegisterView

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls'))
]

app/flights/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class AircraftType(models.Model):
    manufacturer = models.CharField(
        max_length=50,
        verbose_name='Производитель'
    )
    generic_type = models.CharField(
        max_length=50,
        verbose_name='Тип ВС'
    )

    class Meta:
        verbose_name = 'Тип самолета'
        verbose_name_plural = 'Типы самолетов'
        unique_together = ('manufacturer', 'generic_type')

    def __str__(self):
        return f'{self.manufacturer} {self.generic_type}'


class Airline(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,
        verbose_name='Название авиакомпании'
    )

    class Meta:
        verbose_name = 'Авиакомпания'
        verbose_name_plural = 'Авиакомпании'

    def __str__(self):
        return self.name


class Airframe(models.Model):
    serial_number = models.CharField(
        max_length=50,
        verbose_name='Серийный номер'
    )
    registration_number = models.CharField(
        max_length=50,
        verbose_name='Регистрационный номер'
    )

    def get_airframe_image_path(self, filename):
        *old_name, format = filename.split('.')
        new_filename = '.'.join((self.registration_number, format))
        return f'airframes/{self.airline.name}/{new_filename}'.lower()

    photo = models.ImageField(
        upload_to=get_airframe_image_path,
        verbose_name='Фото ВС'
    )
    aircraft_type = models.ForeignKey(
        to='AircraftType',
        on_delete=models.SET_NULL,
        null=True,
        related_name='airframes',
        verbose_name='Тип ВС'
    )
    airline = models.ForeignKey(
        to='Airline',
        on_delete=models.SET_NULL,
        null=True,
        related_name='fleet',
        verbose_name='Авиакомпания'
    )

    class Meta:
        verbose_name = 'Воздушное судно'
        verbose_name_plural = 'Воздушные судна'
        unique_together = ('serial_number', 'registration_number')

    def __str__(self):
        return f'Борт {self.registration_number}'


class FlightInfo(models.Model):
    DEPARTURE = 'Departure'
    ARRIVAL = 'Arrival'
    STATUS_CHOICES = [
        (DEPARTURE, 'Departure'),
        (ARRIVAL, 'Arrival'),
    ]

    flight = models.ForeignKey(
        to='Flight',
        on_delete=models.CASCADE,
        verbose_name='Полет'
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        verbose_name='Вылет/Прилет'
    )
    airport_code = models.CharField(
        max_length=4,
        verbose_name='IATA-код аэропорта'
    )
    metar = models.CharField(
        max_length=300,
        verbose_name='METAR',
        blank=True,
        null=True
    )
    gate = models.CharField(
        max_length=5,
        verbose_name='Гейт',
        blank=True,
        null=True
    )
    is_boarding_bridge = models.BooleanField(
        verbose_name='Через телетрап',
        default=False
    )
    schedule_time = models.TimeField(
        verbose_name='Время рассчетное',
        blank=True,
        null=True
    )
    actual_time = models.TimeField(
        verbose_name='Время фактическое',
        blank=True,
        null=True
    )
    runway = models.CharField(
        max_length=3,
        verbose_name='Активная ВПП'
    )

    class Meta:
        verbose_name = 'Дополнительная информация о полете'
        verbose_name_plural = 'Дополнительная информация о полете'
        unique_together = ('flight', 'airport_code')

    def __str__(self):
        tail = self.status + ': ' + self.airport_code
        return f'{self.flight.__str__()}/{tail}'


class Flight(models.Model):
    flight_number = models.CharField(
        max_length=50,
        verbose_name='Номер рейса'
    )
    airframe = models.ForeignKey(
        to='Airframe',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Воздушное судно'
    )

    date = models.DateField(
        verbose_name='Дата полета',
    )

    flight_time = models.TimeField(
        verbose_name='Время полета',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Совершенный полет'
        verbose_name_plural = 'Совершенные полеты'
        unique_together = ('flight_number', 'date')

    def __str__(self):
        return f'Совершенный полет {self.flight_number}/{self.date}'

    def delete(self, using=None, keep_parents=False):
        airframe = self.airframe
        other_flight_count = Flight.objects.filter(airframe=airframe).exclude(pk=self.pk).count()
        if other_flight_count == 0:
            airframe.delete(using=using, keep_parents=keep_parents)
        super(Flight, self).delete(using=using, keep_parents=keep_parents)


class UserTrip(models.Model):
    flight = models.ForeignKey(
        to='Flight',
        on_delete=models.CASCADE,
        verbose_name='Полет'
    )
    passenger = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name='Пассажир'
    )
    seat = models.CharField(
        max_length=4,
        verbose_name='Место',
        blank=True,
        null=True
    )
    neighbors = models.TextField(
        verbose_name='Соседи в полете',
        blank=True,
        null=True
    )
    comments = models.TextField(
        verbose_name='Комментарии',
        blank=True,
        null=True
    )
    price = models.PositiveIntegerField(
        verbose_name='Цена билета',
        blank=True,
        null=True
    )
    slug = models.SlugField(
        blank=True,
        verbose_name='Слаг'
    )

    class Meta:
        verbose_name = 'Путешествие пользователя'
        verbose_name_plural = 'Путешествия пользователей'
        unique_together = ('flight', 'passenger')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.flight.flight_number}-{self.flight.date}-{self.passenger.username}")

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Путешествие {self.flight.flight_number}-{self.flight.date}-{self.passenger.username}"

    def delete(self, using=None, keep_parents=False):
        flight = self.flight
        other_usertrip_count = UserTrip.objects.filter(flight=flight).exclude(pk=self.pk).count()
        if other_usertrip_count == 0:
            flight.delete(using=using, keep_parents=keep_parents)
        super(UserTrip, self).delete(using=using, keep_parents=keep_parents)


class TrackImage(models.Model):
    trip = models.ForeignKey(
        to='UserTrip',
        on_delete=models.CASCADE,
        verbose_name='Полет пользователя'
    )

    def get_airframe_image_path(self, filename):
        return f'tracks/{self.trip.passenger.username}/' \
               f'{self.trip.flight.flight_number}/' \
               f'{self.trip.flight.date}/' \
               f'{filename}'.lower()

    track_img = models.ImageField(
        upload_to=get_airframe_image_path,
        verbose_name='Изображение трэка',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Изображения трэка'
        verbose_name_plural = 'Изображения трэков'

    def __str__(self):
        return f'Трэк {str(self.track_img.url)}'


class Meal(models.Model):
    trip = models.ForeignKey(
        to='UserTrip',
        on_delete=models.CASCADE,
        verbose_name='Путешествие',
        default=1
    )
    drinks = models.TextField(verbose_name='Предложенные напитки', default='Вода')
    appertize = models.TextField(verbose_name='Предложенные закуски', default='')
    main_course = models.TextField(verbose_name='Основные блюда', default='')
    desert = models.TextField(verbose_name='Предложенные десерты', default='')
    meal_price = models.PositiveSmallIntegerField(
        verbose_name='Цена питания',
        blank=True,
        null=True
    )

    def get_airframe_image_path(self, filename):
        return f'meal/{self.trip.flight.flight_number}/' \
               f'{self.trip.flight.date}/' \
               f'{filename}'.lower()

    meal_photo = models.ImageField(
        upload_to=get_airframe_image_path,
        verbose_name='Фотография питания',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Питание в полете'
        verbose_name_plural = 'Питание в полете'

    def __str__(self):
        return f'Питание на рейсе {self.trip.flight.flight_number}/{self.trip.flight.date}'

app/templates/flights/add_flight.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
<div class="container">
  <h1>{{ title }}</h1>
  <br>

  <form action="{% if url_args %}{% url view_name url_args %}{% else %}{% url view_name %}{% endif %}"
        method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="alert text-center">
      Fields marked with * are required
    </div>

    <div class="text-center mb-3">
      <button type="submit" class="btn btn-success">Submit</button>
    </div>

    {% if form.errors %}
        <div class="alert alert-warning text-center" role="alert">
          {% for field in form %}
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          {% endfor %}
        </div>
    {% endif %}

    <ul class="nav nav-tabs" id="myTabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="tab1-tab" data-toggle="tab" href="#tab1" role="tab" aria-controls="tab1" aria-selected="true">Flight Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="tab2-tab" data-toggle="tab" href="#tab2" role="tab" aria-controls="tab2" aria-selected="false">Feelings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="tab3-tab" data-toggle="tab" href="#tab3" role="tab" aria-controls="tab3" aria-selected="false">Meal</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="tab4-tab" data-toggle="tab" href="#tab4" role="tab" aria-controls="tab4" aria-selected="false">Flight Conditions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="tab5-tab" data-toggle="tab" href="#tab5" role="tab" aria-controls="tab5" aria-selected="false">Flight Tracks</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
          {% include 'include/tab1.html' %}
      </div>

      <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
          {% include 'include/tab2.html' %}
      </div>

      <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="tab3-tab">
          {% include 'include/tab3.html' %}
      </div>

      <div class="tab-pane fade" id="tab4" role="tabpanel" aria-labelledby="tab4-tab">
          {% include 'include/tab4.html' %}
      </div>

      <div class="tab-pane fade" id="tab5" role="tabpanel" aria-labelledby="tab5-tab">
          <div id="fields-container">
              {{ formset.management_form }}

              {% for f in formset %}
                {{ f.as_p }}
              {% endfor %}
          </div>
      </div>

    </div>
  </form>
</div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/tabs.js' %}"></script>
    <script src="{% static 'js/image_forms.js' %}"></script>
{% endblock scripts %}

app/templates/flights/flight.html
{% extends 'base.html' %}


{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'css/modal.css' %}">
{% endblock styles %}


{% block content %}
<!-- Block Content -->
<div class="container-fluid" style="max-width: 40%; margin: 0 auto;">
    <table class="table table-striped main-table">
      <thead>
        <tr>
          <th colspan="2"><img src="{{ MEDIA_URL }}{{ flight.airframe_photo }}" alt="Фото самолета" style="display: block; margin: 0 auto; max-height: 150px;"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="width: 40%">Авиакомпания</td>
          <td style="width: 60%">{{ flight.airline_name }}</td>
        </tr>
        <tr>
          <td>Тип ВС</td>
          <td>{{ flight.aircraft_type }}</td>
        </tr>
        <tr>
          <td>Бортовой номер</td>
          <td>{{ flight.registration_number }}</td>
        </tr>
        <tr>
          <td>Номер рейса</td>
          <td>{{ flight.flight_number }}</td>
        </tr>
        <tr>
          <td>Дата</td>
          <td>{{ flight.date }}</td>
        </tr>
        <tr>
          <td>Маршрут</td>
          <td>{{ flight.route }}</td>
        </tr>
        <tr>
          <td>Время полета</td>
          <td>{{ flight.flight_time }}</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Пассажир</td>
          <td>{{ flight.user }}</td>
        </tr>
        <tr>
          <td>Место</td>
          <td>{{ flight.seat }}</td>
        </tr>
        <tr>
          <td>Соседи</td>
          <td>{{ flight.neighbors }}</td>
        </tr>
        <tr>
          <td>Комментарии</td>
          <td>{{ flight.comments }}</td>
        </tr>
        <tr>
          <td>Стоимость билета, руб</td>
          <td>{{ flight.ticket_price }}</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Прохладительные напитки</td>
          <td>{{ flight.drinks }}</td>
        </tr>
        <tr>
          <td>Закуски</td>
          <td>{{ flight.appertize }}</td>
        </tr>
        <tr>
          <td>Основное блюдо</td>
          <td>{{ flight.main_course }}</td>
        </tr>
        <tr>
          <td>Десерт</td>
          <td>{{ flight.desert }}</td>
        </tr>
        <tr>
          <td>Стоимость питания, руб</td>
          <td>{{ flight.meal_price }}</td>
        </tr>
        {% if flight.meal_photo %}
          <tr>
            <th colspan="2"><img src="{{ MEDIA_URL }}{{ flight.meal_photo }}" alt="Фото питания" style="display: block; margin: 0 auto; max-height: 150px;"></th>
          </tr>
        {% endif %}
      </tbody>
    </table>
</div>


<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="container-fluid" style="max-width: 50%; margin: 0 auto;">
      <table class="table table-striped info-table">
        <thead>
          <tr>
            <th colspan="2">Условия вылета</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style="width: 40%">Аэропорт (IATA)</td>
            <td style="width: 60%">{{ flight.departure_info.airport_code }}</td>
          </tr>
          <tr>
            <td>Гейт</td>
            <td>{{ flight.departure_info.gate }}</td>
          </tr>
          <tr>
            <td>Через телетрап</td>
            <td>{{ flight.departure_info.is_boarding_bridge }}</td>
          </tr>
          <tr>
            <td>Время расчетное</td>
            <td>{{ flight.departure_info.schedule_time }}</td>
          </tr>
          <tr>
            <td>Время фактическое</td>
            <td>{{ flight.departure_info.actual_time }}</td>
          </tr>
          <tr>
            <td>Активная ВПП</td>
            <td>{{ flight.departure_info.runway }}</td>
          </tr>
          <tr>
            <td>METAR</td>
            <td>{{ flight.departure_info.metar }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <div class="container-fluid" style="max-width: 50%; margin: 0 auto;">
      <table class="table table-striped info-table">
        <thead>
          <tr>
            <th colspan="2">Условия прилета</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style="width: 40%">Аэропорт (IATA)</td>
            <td style="width: 60%">{{ flight.arrival_info.airport_code }}</td>
          </tr>
          <tr>
            <td>Гейт</td>
            <td>{{ flight.arrival_info.gate }}</td>
          </tr>
          <tr>
            <td>Через телетрап</td>
            <td>{{ flight.arrival_info.is_boarding_bridge }}</td>
          </tr>
          <tr>
            <td>Время расчетное</td>
            <td>{{ flight.arrival_info.schedule_time }}</td>
          </tr>
          <tr>
            <td>Время фактическое</td>
            <td>{{ flight.arrival_info.actual_time }}</td>
          </tr>
          <tr>
            <td>Активная ВПП</td>
            <td>{{ flight.arrival_info.runway }}</td>
          </tr>
          <tr>
            <td>METAR</td>
            <td>{{ flight.arrival_info.metar }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="image-container">
    {% for track in flight.track_images %}
      <img src="{{ MEDIA_URL }}{{ track.track_img }}" alt="Track {{ forloop.counter }}" style="max-height: 150px;">
    {% endfor %}
  </div>
</div>

<!-- Кнопки и ссылки -->
<div class="container mt-4">
  <div class="row justify-content-end">
    <div class="col-md-12">
      {% if user.is_authenticated and flight.user.username == user.username %}
        <div class="button-container text-right">
          <a href="{% url 'flight_update' flight.usertripslug %}" class="btn btn-primary">Edit</a>

          <form action="{% url 'flight_delete' flight.usertripslug %}" method="post" class="d-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
          
          <a href="#" class="btn btn-secondary">Get in PDF</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}


{% block scripts %}
  <script src="{% static 'js/modal_screen.js' %}"></script>
{% endblock scripts %}


Что должно быть на странице

одна узкая таблица, в которой два стобца:
1 строка: объединенные столбцы, в ячейке помещается фото самолета
2 строка: авиакомпания - название АК
3 строка: номер рейса
4 строка: дата
5 строка: тип ВС
6 строка: пункт отправления и пункт назначения (IATA)
7 строка: пустая (для разграничения)
8 строка: место
9 строка: соседи
10 строка: комментарии
11 строка: стоимость
12 строка пустая (для разграничения)
13 строка прохладительные напитки
14 строка закуски
15 основное блюдо
16 строка десерт
17 строка: фото питания, помещается в объединенные ячейки


1 строка: аэропорт (IATA)
2 строка: METAR
3 строка: гейт
4 строка: через телетрап (bool)
5 строка: время расчетное
6 строка: время фактическое

app/templates/flights/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Block Content -->
<div class="container mt-3">
  <div class="row">

    <!-- Sidebar -->
    {% include 'include/sidebar_main.html' %}

    <!-- Main Content -->
    <div class="col-md-9">

      {% if not user.is_authenticated %}
        <div class="alert alert-warning text-center" role="alert">
          Attention! Adding (editing and deleting) flight records is only possible for authorized users!
        </div>
      {% endif %}

      <h4>Latest Flights</h4>
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for card in latest_cards %}
          <div class="col">
            <div class="card h-100">
              <img src="{{ MEDIA_URL }}{{ card.photo_url }}" class="card-img-top" alt="..." style="max-height: 250px;">
              <div class="card-body d-flex flex-column justify-content-end">
                <h5 class="card-title">Flight Information</h5>
                <p class="card-text">
                  <strong>Flight Number:</strong> {{ card.flight_number }}<br>
                  <strong>Date:</strong> {{ card.date }}<br>
                  <strong>Passenger:</strong> {{ card.passenger }}<br>
                </p>
                <hr>
                <p class="card-text">
                  <small>Airline: {{ card.airline }}</small><br>
                  <small>Aircraft Type: {{ card.aircraft_type }}</small><br>
                  <small>Departure: {{ card.departure }}</small><br>
                  <small>Destination: {{ card.destination }}</small>
                </p>
              </div>
              <div class="card-footer">
                <a href="{% url 'flight' card.usertripslug %}" class="btn btn-primary">See more</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/flights/passengers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Block Content -->
<div class="container">
  <h1 class="text-center mb-5">List of Passengers</h1>
  <p>Filter by first letter:</p>
  <input type="text" id="filter-input" class="form-control mb-3">

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nickname</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Total Flights</th>
        <th>Unique Aircraft Types</th>
        <th>Unique Airlines</th>
        <th>Unique Airports</th>
      </tr>
    </thead>
    <tbody>
      {% for passenger in passengers %}
        <tr>
          <td><a href="{% url 'profile' passenger.username %}">{{ passenger.username }}</a></td>
          <td>{{ passenger.first_name }}</td>
          <td>{{ passenger.last_name }}</td>
          <td>{{ passenger.total_flights }}</td>
          <td>{{ passenger.total_aircraft_types }}</td>
          <td>{{ passenger.total_airlines }}</td>
          <td>{{ passenger.total_airports }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/search_username.js' %}"></script>
{% endblock scripts %}

app/templates/flights/profile.html
{% extends 'base.html' %}
{% load static %}

<style>
    .center-image {
        display: block;
        margin: 0 auto;
        max-width: 50%;
    }
</style>

{% block content %}
<!-- Block Content -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="{% static 'images/avatar_default.png' %}" class="card-img-top center-image" alt="Avatar" style="max-width: 50%;">
                <div class="card-body">
                    <p class="card-text">Username: {{ profile.username }}</p>
                    <p class="card-text">First Name: {{ profile.first_name }}</p>
                    <p class="card-text">Last Name: {{ profile.last_name }}</p>
                    <p class="card-text"><i class="fas fa-plane"></i> Flights: {{ profile.total_flights }}</p>
                    <p class="card-text"><i class="fas fa-plane-departure"></i> Airlines: {{ profile.total_airlines }}</p>
                    <p class="card-text"><i class="fas fa-plane-arrival"></i> Aircraft Types: {{ profile.total_aircraft_types }}</p>
                    <p class="card-text"><i class="fas fa-plane-arrival"></i> Airports Visited: {{ profile.total_airports }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Airline</th>
                    <th>Flight No.</th>
                    <th>Date</th>
                    <th>Departure airport (IATA)</th>
                    <th>Destination airport (IATA)</th>
                </tr>
                </thead>
                <tbody>
                {% for flight in flights %}
                    <tr onclick="location.href='{% url 'flight' flight.slug %}';">
                        <td>{{ flight.flight.airframe.airline.name }}</td>
                        <td>{{ flight.flight.flight_number }}</td>
                        <td>{{ flight.flight.date|date:"d-m-Y" }}</td>
                        {% for flight_info in flight.flight.flightinfo_set.all %}
                            {% if flight_info.status == 'Departure' %}
                                <td>{{ flight_info.airport_code }}</td>
                            {% endif %}
                            {% if flight_info.status == 'Arrival' %}
                                <td>{{ flight_info.airport_code }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}